### ISSUE TITLE
Add an option to specify where to grab the headings to build the table of contents

### ISSUE THREAD

**Issue by bobmitro** [psalmody/html-contents#1]
Hi,
First of all, thank you for your work; your TOC script works very smoothly. 

What I would like to see is:
- the ability to specify the container from which the script grabs headers to build a table of contents
- active CSS class added to the selected TOC element (item)

Could you provide us with these features?

**Comment by psalmody** [comment]
@bobmitro Thanks for using the package.

So I've just added the ability to use filter option as a function. You could use a combination of that filter function and [Node.contains](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) to filter the selector. 

For adding an active CSS class: writing a click handler for any links within the element would probably be the way to go. I don't think I'll add that as a function here since it's a little out of scope for this package.

Thanks for the suggestions!
